repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff-lint
        args: [lint]
        stages: [commit, push]
      - id: ruff-format
        name: ruff-format
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: mypy-strict
        args:
          - "--strict"

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: detect-secrets
        args:
          - "--baseline"
          - ".secrets.baseline"
        exclude: |
          ^docs/
